import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

import 'package:orchestrate_app/core/theme/app_theme.dart';
import 'package:orchestrate_app/features/public/widgets/operational_flow_diagram.dart';

/// Public "How Orchestrate operates" surface, rendered as a visual
/// operational flow diagram + cross-links to the trust + activation
/// surfaces. Replaces the text-only PublicContentScreen for this route
/// so the visitor sees infrastructure progression, not paragraphs.
class OrchestrateOperationsScreen extends StatelessWidget {
  const OrchestrateOperationsScreen({super.key});

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    return Padding(
      padding: const EdgeInsets.fromLTRB(28, 28, 28, 40),
      child: Center(
        child: ConstrainedBox(
          constraints: const BoxConstraints(maxWidth: 1180),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              _Hero(theme: theme),
              const SizedBox(height: 24),
              OperationalFlowDiagram(stages: _operationalStages()),
              const SizedBox(height: 24),
              _CrossLinks(theme: theme),
              const SizedBox(height: 24),
              _OperationalGuaranteesSection(theme: theme),
            ],
          ),
        ),
      ),
    );
  }

  List<OperationalFlowStage> _operationalStages() => const [
        OperationalFlowStage(
          label: 'Domain attached',
          ownership: 'client',
          body:
              'The client confirms or attaches the sending domain. Orchestrate creates a SendingDomain row and surfaces the SPF, DKIM, and DMARC records to publish. Domain identity is the operational center; transports plug in beneath.',
          bullets: [
            'Inferred from Representation profile when available',
            'Manual entry supported for clients with separate sending infrastructure',
            'No transport required to begin DNS verification',
          ],
        ),
        OperationalFlowStage(
          label: 'DNS verified',
          ownership: 'orchestrate',
          body:
              'Live DNS lookups verify SPF, DKIM, and DMARC. A polling worker re-checks pending domains automatically and records per-record propagation history.',
          bullets: [
            'node:dns queries, no third-party deliverability vendor',
            'Per-record verification history kept for audit',
            'Trust classification: pending → limited → warmup → full-trust',
          ],
        ),
        OperationalFlowStage(
          label: 'Transport connected',
          ownership: 'client',
          body:
              'Three first-class transports: Google Workspace OAuth, Microsoft 365 OAuth, or custom SMTP + IMAP. Credentials are sealed by an encrypted vault adapter; OAuth runs entirely backend-side. Custom SMTP gets a per-transport DKIM keypair generated by Orchestrate, and IMAP cursors seed at the current highest UID so no historical inbox is inspected.',
          bullets: [
            'OAuth: send-only scope (no inbox read)',
            'Custom SMTP + IMAP: per-transport DKIM, header-first ingestion',
            'Encrypted vault, no browser exposure, no plaintext DB',
          ],
        ),
        OperationalFlowStage(
          label: 'Readiness governed',
          ownership: 'orchestrate',
          body:
              'A single backend authority evaluates the eight-layer dependency chain. Every client surface (Operations, Infrastructure, Settings, Home, guidance drawer) reads from this one authority, so readiness never drifts per screen.',
          bullets: [
            'Setup → billing → representation → identity → domain → trust → transport → dispatch',
            'Per-layer state: ready / pending / waiting / blocked',
            'Inline resolution CTA on every client-pending layer',
          ],
        ),
        OperationalFlowStage(
          label: 'Outbound execution activated',
          ownership: 'orchestrate',
          body:
              'When every layer is ready, dispatch eligibility flips. Messages are generated against the business identity, paced under a per-mailbox governor, DKIM-signed at the adapter, and stamped with a custom operation-id header so reply matching survives relays.',
          bullets: [
            'Suppression check at every send',
            'Per-mailbox in-flight cap (governed pacing)',
            'DKIM signing inside Orchestrate, not delegated to the relay',
          ],
        ),
        OperationalFlowStage(
          label: 'Replies matched',
          ownership: 'orchestrate',
          body:
              'IMAP ingestion runs operation-scoped. Phase 1 reads headers only; phase 2 matches inbound to this client\'s outbound via In-Reply-To / References / operation-id header; phase 3 fetches bodies ONLY for matched UIDs. Unmatched mail stays in the upstream mailbox — body never read.',
          bullets: [
            'Header-first, body-on-match-only',
            'Deduplication keyed by upstream message-id',
            'No general inbox reading',
          ],
        ),
        OperationalFlowStage(
          label: 'Follow-ups governed',
          ownership: 'orchestrate',
          body:
              'A matched reply cancels queued FOLLOWUP_SEND jobs and SCHEDULED OutreachMessage rows targeting the same lead. The platform stops dispatching the moment a recipient responds.',
        ),
        OperationalFlowStage(
          label: 'Suppression enforced',
          ownership: 'orchestrate',
          body:
              'UNSUBSCRIBE / HARD_BOUNCE / COMPLAINT / MANUAL_BLOCK entries block every FIRST_SEND, FOLLOWUP_SEND, and direct email. No code path bypasses suppression.',
        ),
        OperationalFlowStage(
          label: 'Operational continuity maintained',
          ownership: 'orchestrate',
          body:
              'When something degrades — OAuth revoked, SMTP throttle, DNS regression — the readiness chain names the dependency, ownership, and concrete next action. Recovery branches re-converge readiness without client lifecycle controls.',
          bullets: [
            'Append-only audit trail across vault, connect, reply, suppression',
            'Recovery is Orchestrate-owned by default',
            'No fake "everything green" while a subsystem is degraded',
          ],
        ),
      ];
}

class _Hero extends StatelessWidget {
  const _Hero({required this.theme});

  final ThemeData theme;

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.all(32),
      decoration: BoxDecoration(
        color: AppTheme.publicSurface,
        borderRadius: BorderRadius.circular(AppTheme.radius),
        border: Border.all(color: AppTheme.publicLine),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Container(
            padding:
                const EdgeInsets.symmetric(horizontal: 12, vertical: 6),
            decoration: BoxDecoration(
              color: AppTheme.publicAccentSoft,
              borderRadius: BorderRadius.circular(999),
            ),
            child: Text(
              'How Orchestrate operates',
              style: theme.textTheme.labelLarge?.copyWith(
                color: AppTheme.publicAccent,
                fontWeight: FontWeight.w700,
              ),
            ),
          ),
          const SizedBox(height: 16),
          Text(
            'Identity → trust → transport → readiness → governed execution → continuity.',
            style: theme.textTheme.headlineSmall?.copyWith(
              fontWeight: FontWeight.w700,
            ),
          ),
          const SizedBox(height: 8),
          ConstrainedBox(
            constraints: const BoxConstraints(maxWidth: 720),
            child: Text(
              'A linear walkthrough of what actually happens after a client '
              'connects identity to the platform. Every layer below maps to '
              'real runtime behavior — operational truth, not feature copy.',
              style: theme.textTheme.bodyLarge
                  ?.copyWith(color: AppTheme.publicMuted),
            ),
          ),
        ],
      ),
    );
  }
}

class _CrossLinks extends StatelessWidget {
  const _CrossLinks({required this.theme});

  final ThemeData theme;

  @override
  Widget build(BuildContext context) {
    return Wrap(
      spacing: 12,
      runSpacing: 12,
      children: [
        FilledButton(
          onPressed: () => context.go('/why-orchestrate'),
          child: const Text('Why Orchestrate exists'),
        ),
        OutlinedButton(
          onPressed: () => context.go('/trust-architecture'),
          child: const Text('Trust architecture'),
        ),
        OutlinedButton(
          onPressed: () => context.go('/pricing'),
          child: const Text('Pricing'),
        ),
        TextButton(
          onPressed: () => context.go('/auth/join?trial=15d'),
          child: const Text('Start 15-Day Trial →'),
        ),
      ],
    );
  }
}

class _OperationalGuaranteesSection extends StatelessWidget {
  const _OperationalGuaranteesSection({required this.theme});

  final ThemeData theme;

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.all(28),
      decoration: BoxDecoration(
        color: AppTheme.publicSurfaceSoft,
        borderRadius: BorderRadius.circular(AppTheme.radius),
        border: Border.all(color: AppTheme.publicLine),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            'Operational guarantees this flow encodes',
            style: theme.textTheme.titleLarge
                ?.copyWith(fontWeight: FontWeight.w700),
          ),
          const SizedBox(height: 14),
          for (final item in _guarantees) ...[
            Padding(
              padding: const EdgeInsets.symmetric(vertical: 4),
              child: Row(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Container(
                    margin: const EdgeInsets.only(top: 7, right: 12),
                    width: 6,
                    height: 6,
                    decoration: const BoxDecoration(
                      color: AppTheme.publicAccent,
                      shape: BoxShape.circle,
                    ),
                  ),
                  Expanded(
                    child: Text(
                      item,
                      style: theme.textTheme.bodyMedium
                          ?.copyWith(color: AppTheme.publicText, height: 1.4),
                    ),
                  ),
                ],
              ),
            ),
          ],
        ],
      ),
    );
  }

  static const _guarantees = <String>[
    'No body of an inbox message is ever read unless it resolves to a known operation',
    'No outbound is dispatched to a suppressed recipient',
    'No claim of "ready" while any dependency in the chain is unresolved',
    'No credential is exposed in API responses, logs, or browser state',
    'No AI invocation receives mailbox content that is not operation-attributed',
    'No silent transport failure — every degraded state names its owner + next action',
  ];
}
